import fs from 'fs'
import path from 'path'
import { toCamel } from './env'

/**
 * 生成声明体
 * @param envDict 环境变量集
 * @returns 声明代码串
 */
export function genDts(envDict: Record<string, string>): string {
	const envLines = Object.entries(envDict)
		.map(([key, value]) => {
			const displayVal = value.includes('\n') ? value.split('\n')[0] + '...' : value
			return `\t\t/** 原始配置值 \`${displayVal}\` */\n\t\t${key}: string`
		})
		.join('\n')

	const camelLines = Object.entries(envDict)
		.map(([key, value]) => {
			const displayVal = value.includes('\n') ? value.split('\n')[0] + '...' : value
			return `\t\t/** 对应 \`${key}\` (配置值 \`${displayVal}\`) */\n\t\t${toCamel(key)}: string`
		})
		.join('\n')

	return `/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by @hlw-mp/vite-plugin. Do not edit directly.

declare global {
	const __APP_NAME__: string
	const __APP_VERSION_CODE__: number
	const __APP_VERSION_NAME__: string
	const __APP_BASE_URL__: string
	const __APP_WSS_URL__: string
	const __APPID__: string

	interface HostEnvMap {
${envLines}
		[key: string]: unknown
	}

	interface HostEnvCamelMap {
${camelLines}
		[key: string]: unknown
	}

	type HostEnv = HostEnvMap & HostEnvCamelMap
	type HostEnvKey = keyof HostEnvMap | keyof HostEnvCamelMap | string
}

export type { HostEnvMap, HostEnvCamelMap, HostEnv, HostEnvKey }
`
}

/**
 * 写入声明体
 * @param targetFile 目标文件径
 * @param fileCode 目标代码串
 */
export function writeDts(targetFile: string, fileCode: string): void {
	const directoryPath = path.dirname(targetFile)
	if (!fs.existsSync(directoryPath)) {
		fs.mkdirSync(directoryPath, { recursive: true })
	}
	if (fs.existsSync(targetFile)) {
		const oldContent = fs.readFileSync(targetFile, 'utf-8')
		if (oldContent === fileCode) return
	}
	fs.writeFileSync(targetFile, fileCode, 'utf-8')
}
